/*
 * Copyright 2012 Red Hat
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package org.blogdemo.mqtt.drools;

import org.blogdemo.mqtt.model.BloodPressure;

rule "Prehypertension"
when
    bp : BloodPressure( bloodpressure >= 120 )
then
	bp.setCategory(1);
	bp.setCategoryDesc("Prehypertension");
end


rule "High Blood Pressure"
when
    bp : BloodPressure( bloodpressure >= 160 )
then
	bp.setCategory(2);
	bp.setCategoryDesc("High Blood Pressure");
end


rule "Hypertensive Crisis"
when
    bp : BloodPressure( bloodpressure >= 180 )
then
	bp.setCategory(3);
	bp.setCategoryDesc("Hypertensive Crisis");
end
