/*
 * Copyright 2012 Red Hat
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package org.blogdemo.mqtt.drools;

import org.blogdemo.mqtt.model.InsulinPump;

rule "Blood Sugar too low"
when
    ip : InsulinPump( insulinPump < 4.0 )
then
	ip.setCategory(0);
	ip.setCategoryDesc("Prehypertension");
end


rule "Diabetes"
when
    ip : InsulinPump( insulinPump >= 6.0 )
then
	ip.setCategory(2);
	ip.setCategoryDesc("Diabetes");
end


